#!/usr/bin/env bash

# Update the package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Create a sample HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html
