#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

x=0
while [[ $x -ne 10 ]]; do
    echo "Best School"
    if [[ $x -eq 8 ]]; then
        echo "Hi"
    fi
    ((x++))
done
